# Nixpacks 配置文件
version: 1

build:
  # 设置更长的构建超时时间
  timeout: 1800
  
  # 使用缓存来加速构建
  cache:
    - /root/.npm
    - /app/node_modules
  
  # 构建阶段配置
  phases:
    setup:
      # 安装系统依赖
      aptPackages:
        - libnss3
        - libatk1.0-0
        - libatk-bridge2.0-0
        - libcups2
        - libgbm1
        - libasound2t64
        - libpangocairo-1.0-0
        - libxss1
        - libgtk-3-0
        - libxshmfence1
        - libglu1
        - chromium
    
    install:
      # 使用 npm install 而不是 npm ci，避免锁文件问题
      - cd server && npm install --prefer-offline --no-audit
    
    build:
      # 构建阶段（如果有需要）
      - echo "Build completed"

# 启动命令
start: cd server && npm start